### ISSUE TITLE
Problem in SnakeSegments struct

### ISSUE THREAD

**Issue by mskf1383** [marcusbuffett/bevy_snake#10]
Hi
Thank you for your great post. in **Adding a tail** part, you define the `SnakeSegments` wrong and it cause to error in **Making the tail follow the snake**:
```rust
#[derive(Default)]
struct SnakeSegments(Vec<Entity>);
```

But I found that the code in Github is true and don't cause to error:
```rust
#[derive(Default, Deref, DerefMut)]
struct SnakeSegments(Vec<Entity>);
```

Please update the post.
Thanks!

**Comment by marcusbuffett** [comment]
Updated, thanks for the catch!
