### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by DuckyBlender** [marcusbuffett/bevy_snake#12]
Your website is down, it takes me to an nginx page :)

**Comment by marcusbuffett** [comment]
Thanks for letting me know, fixed :)

**Comment by DuckyBlender** [comment]
By the way, I'm making a TON of improvements to your game in my fork. I've made a pull request (#11) for the features you may like but I already have v0.8 on my fork with a configurable amount of max food, optimizations & more. I even have a fork for a WebUI at https://duckyblender.github.io/bevy_snake/
 You really should consider my pull request tho, mainly just crate updates and a scoreboard ;)
