### ISSUE TITLE
responsiveness

### ISSUE THREAD

**Issue by boneskull** [marcusbuffett/bevy_snake#2]
Thanks for this tutorial!  It was a great intro to bevy (and ECS).

While playing, I noticed that sometimes my keyboard input is missed when I'm typing quickly.  I think this is because input is only checked when the movement timer fires.

I found some example [input handling code](https://github.com/jamadazi/bevy-cookbook/blob/master/bevy-cookbook.md#input-handling) and thought I would try this instead--basically, it looks like I'd be keeping the most-recently-pressed key in the program state.  So I created a resource for this:

```rust
pub struct InputState {
  pub keys: EventReader<KeyboardInput>,
  pub direction: SnakeDirection, // I renamed Direction to SnakeDirection due to a potential conflict from bevy's prelude
}

impl Default for InputState {
  fn default() -> Self {
    Self {
      keys: EventReader::<KeyboardInput>::default(),
      direction: SnakeDirection::Up,
    }
  }
}
```

And a system:

```rust
pub fn input(
  mut state: ResMut<InputState>,
  ev_keys: Res<Events<KeyboardInput>>,
) {
  for ev in state.keys.iter(&ev_keys) {
    if ev.state.is_pressed() {
      let key_code = ev.key_code.unwrap();
      state.direction = match key_code {
        KeyCode::Left => Some(SnakeDirection::Left),
        KeyCode::Right => Some(SnakeDirection::Right),
        KeyCode::Up => Some(SnakeDirection::Up),
        KeyCode::Down => Some(SnakeDirection::Down),
        _ => None,
      }
      .unwrap_or(state.direction);
    }
  }
}
```

And changed the movement system's signature:

```rust
pub fn snake_movement(
  input: Res<InputState>,
  snake_timer: ResMut<SnakeMoveTimer>,
  segments: ResMut<SnakeSegments>,
  mut last_tail_position: ResMut<LastTailPosition>,
  mut game_over_events: ResMut<Events<GameOverEvent>>,
  mut heads: Query<(Entity, &mut SnakeHead)>,
  mut positions: Query<&mut Position>,
) {
  if !snake_timer.0.finished {
    return;
  }
  for (head_entity, mut head) in heads.iter_mut() {
    let mut head_pos = positions.get_mut(head_entity).unwrap();
    let dir = input.direction;
    if dir != head.direction.opposite() {
      head.direction = dir;
    }
    // ...
```

With the new code above, the snake doesn't drop input _as much_, but it still misses some.  This feels like I'm on the right track, anyway.

If you don't mind me asking:

1. Why might it still be skipping some keyboard input?
1. How could I debug this?

Anyway, I realize your time is valuable and I don't expect a response.  Thanks again for this tutorial.

**Comment by marcusbuffett** [comment]
Thanks for the kind words! Glad you found it useful :) . You're absolutely right that the input logic is messed up and causes the dropped inputs. I've updated the system to check the timer after looking for input, which should accomplish the same goal as your approach (your approach seems equally valid, and actually fixes an issue with it being possible to turn the snake 180, but the tutorial's already so long, trying to conserve space somewhat): https://github.com/marcusbuffett/bevy_snake/blob/tutorial-0.3/src/main.rs#L162 .

In terms of debugging the remaining issue with dropped keystrokes... I'm not really sure, sorry. My best guess would just be to log the keys coming in and see if the issue is there, but I'm sure that's not something you haven't tried / wouldn't have thought of. Do let me know if you figure it out, sorry I don't have the knowledge to be of more help.

**Comment by joonazan** [comment]
The reason why keystrokes are dropped is that you check `pressed`, which I believe is only true if the key is still down. `just_pressed` or `just_released` would be more appropriate. They are true if a keydown or key release has happened between the current and the previous frame.

I am not 100% sure of this because the functions are undocumented but that is the only explanation for their behaviour that makes sense to me.

**Comment by boneskull** [comment]
OK, I experimented with this just now.  Instead of the `input` system above, I changed it to this:

```rust
pub fn input(
  mut state: ResMut<InputState>,
  keyboard_input: Res<Input<KeyCode>>,
) {
  state.direction = if keyboard_input.just_pressed(KeyCode::Left) {
    SnakeDirection::Left
  } else if keyboard_input.just_pressed(KeyCode::Right) {
    SnakeDirection::Right
  } else if keyboard_input.just_pressed(KeyCode::Up) {
    SnakeDirection::Up
  } else if keyboard_input.just_pressed(KeyCode::Down) {
    SnakeDirection::Down
  } else {
    state.direction
  }
}
```

This is more responsive than the original tutorial code, since it's not bound by the movement timer.  _And_ it's more responsive than using `keyboard_input.pressed()` or my code in the description.  `just_pressed()` seems like the best solution (thanks @joonazan).

It looks like what's happening with bevy (correct me if I'm wrong) is that all of these systems are called for every iteration of the game loop.

So the `input` system will continually run, and we'll track the last "relevant" keystroke in the `InputState` resource.

If that's true, it looks like we could even combine this `input` system _and_ the `snake_movement` system by not exiting immediately if the timer is `finished`.

Instead, we could process the keyboard input in `snake_movement` on every tick.  After this, we can check the timer, and if it's finished, then we continue with the snake movement routine, something like:

```rust
pub fn snake_movement(
  mut state: ResMut<InputState>,
  snake_timer: ResMut<SnakeMoveTimer>,
  segments: ResMut<SnakeSegments>,
  mut last_tail_position: ResMut<LastTailPosition>,
  mut game_over_events: ResMut<Events<GameOverEvent>>,
  mut heads: Query<(Entity, &mut SnakeHead)>,
  mut positions: Query<&mut Position>,
) {
  state.direction = if keyboard_input.just_pressed(KeyCode::Left) {
    SnakeDirection::Left
  } else if keyboard_input.just_pressed(KeyCode::Right) {
    SnakeDirection::Right
  } else if keyboard_input.just_pressed(KeyCode::Up) {
    SnakeDirection::Up
  } else if keyboard_input.just_pressed(KeyCode::Down) {
    SnakeDirection::Down
  } else {
    state.direction
  }

  if !snake_timer.0.finished {
    return;
  }

  // continue
}
```


I don't know what's "better", of course...

**Comment by boneskull** [comment]
I'm not sure the use case for `Events<KeyboardInput>`; it seems to give you a sort of "stream" of keyboard events which you can consume.  Obviously, we don't need that here.  Maybe it's more useful if we don't need to assign special behavior to certain keystrokes?  Like typing a character's name into a text box...

**Comment by marcusbuffett** [comment]
@boneskull Looks like we arrived at pretty much the same solution, your 2nd snippet there is how it works in the current code/tutorial, after I updated it yesterday. I prefer your state approach over my approach which changes the direction on the snake, I might steal that :)

**Comment by boneskull** [comment]
You're welcome to it! thanks again.
