### ISSUE TITLE
There is a possibility to ignore opposite direction check

### ISSUE THREAD

**Issue by kifirkin** [marcusbuffett/bevy_snake#4]
It is possible to trick opposite direction check. To do this you need quickly change direction to something different than current and then switch it back, before the `timer.finished` condition is met.

I've played around it a bit, but have no idea how to fix it.

Is there any chance to overcome this issue?

**Comment by marcusbuffett** [comment]
Yeah this is a known issue. At the bottom of the tutorial, this is one of the “homework” items. To fix it, you would need to keep track of one more bit of state. Currently there’s no way to know whether the direction on the head is the direction it’s moving, or a direction the user just entered. If you add a new bit of state that represents the new direction from the user, and don’t update the SnakeHead direction until the tick, then you can deal with the issue.

**Comment by kifirkin** [comment]
Oh sorry I've missed that peace of tutorial 😅 Thanks for the reply!
